#!/bin/bash

export DISPLAY=:0.0
TMPE=$( realpath "$0"  )
cd $(dirname "$TMPE") && cd ../

echo "+ SETTING UP VIRTUAL ENV"
source $(pwd)/venv/bin/activate

cd $(dirname "$TMPE")
which python
python -V

which python | grep -i '/venv/bin/python' &> /dev/null
if [[ $? == 0 ]]; then
   echo "VIRTUAL ENV SET!"
   if [[ $(python -c 'import sys; print(sys.version_info[:][0])') > 2 ]]; then
     echo "+ SETTING UP CONFIGURATIONS FOR THE PROGRAM..."
     eval "python config_init.py"
     echo "+ CHECKING STATIC TICKER STATUS"

      # FOR STATIC TICKER
      TICKER_STATIC=$(cat $(dirname "$TMPE")/config.json | grep static_ticker_condition | awk '{print $2}'|cut -d , -f1)

      if [[ $TICKER_STATIC = "true" ]]; then
        eval "python ticker_gtk.py 2> /dev/null &"
        TICKER_STATIC_PID=$!
      fi
      echo "+ CHECKING MAIN TICKER STATUS"

      # FOR MAIN TICKER
      TICKER_MAIN=$(cat $(dirname "$TMPE")/config.json | grep main_ticker_condition | awk '{print $2}'|cut -d , -f1)
      if [[ $TICKER_MAIN = "true" ]]; then
        eval "echo + CHECKING OPTIONAL TICKER STATUS"

        # FOR OPTIONAL TICKER
        TICKER_MAIN_OPTIONAL=$(cat $(dirname "$TMPE")/config.json | grep optional_ticker_condition | awk '{print $2}'|cut -d , -f1)
        if [[ $TICKER_MAIN_OPTIONAL = "true" ]]; then
          eval "python ticker_main.py 1 &"
          TICKER_MAIN_OPTIONAL_PID=$!
          eval "sleep 0.2s"
        fi
        eval "python ticker_main.py 2 2> /dev/null &"
        TICKER_MAIN_PID=$!
      fi

      # FOR MOVING TICKER
      TICKER_MOVING=$(cat ticker_setup.json | grep moving_ticker_condition | awk '{print $2}'|cut -d , -f1)
      if [[ $TICKER_MOVING = "true" ]]; then
        eval "sleep 0.2s"
        eval "python ticker_animated.py 2> /dev/null &"
        TICKER_MOVING_PID=$!
      fi

      bash $(dirname "$TMPE")/stop_ticker $TICKER_STATIC_PID $TICKER_MAIN_OPTIONAL_PID $TICKER_MAIN_PID $TICKER_MOVING_PID &
	else
	  echo "IMPROPER VERISON OF PYTHON FOUND IN VIRTUAL ENV"
  fi
else
  echo "VIRTUAL ENV NOT ACTIVATED! > EXIT FROM INSTALLATION"
fi

echo " "