#!/bin/bash

for KILLPID in `ps ax | grep 'ticker_animated.py' | awk '{print $1;}'`; do
kill -9 $KILLPID &> /dev/null;
done

for KILLPID in `ps ax | grep 'ticker_main.py' | awk '{print $1;}'`; do
kill -9 $KILLPID &> /dev/null;
done

for KILLPID in `ps ax | grep 'ticker_gtk.py' | awk '{print $1;}'`; do
kill -9 $KILLPID &> /dev/null;
done

for KILLPID in `ps ax | grep 'ticker_emergency.py' | awk '{print $1;}'`; do
kill -9 $KILLPID &> /dev/null;
done

for KILLPID in `ps ax | grep 'start_ticker' | awk '{print $1;}'`; do
kill -9 $KILLPID &> /dev/null;
done

if [[ $1 = "ipad" ]];
then
      echo "NO PARAMETER TO BE PASSED"
else
      echo 'TICKERSTOP' | nc -w 1 localhost 7008
fi

sudo systemctl stop ticker-stop.timer
rm -f /lib/systemd/system/ticker-stop.timer
systemctl daemon-reload
