#!/bin/bash

TMPE=$( realpath "$0"  )
cd $(dirname "$TMPE")

TIME_SLEEP=$(cat ticker_setup.json | grep time_interval | awk '{print $2}'|cut -d , -f1)
sleep $TIME_SLEEP

for a in "$@";
do
kill -9 $a &> /dev/null;
done